development:
  secret_key_base: "amitreejwtsecret"
  referral_base_url: "http://localhost:3000"

production_readonly:
  secret_key_base: "amitreejwtsecret"

test:
  secret_key_base: "amitreejwtsecrettest"

production:
  secret_key_base: <%=  ENV["SECRET_KEY_BASE"] %>
